### ISSUE TITLE
Change symbol for bridge assets to use suffix form

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/assetlists#200]
i.e. USDC.axl instead of axlUSDC

**Comment by JeremyParish69** [comment]
I need to be clear on what is desired:
On the Main assetlist, it does not list Gravity Bridge-bridged assets (except for the GRAV token), and Axelar-bridged Assets was using the axl- prefix. We can change this to either use a suffix, or else no prefix nor suffix at all.
On the Frontier assetlist, the Gravity Bridge-bridged assets are already using the -.grv suffix, and the Axelar-bridged Assets were not using any prefix nor suffix (because it is the canonical).

Should we make both assetlists use the -.axl suffix? Or should we make both assetlists use no prefix nor suffix for Axelar-bridged assets (because canonical)? Or should we make the Frontier assetlist use suffixes but the main assetlist to not use siffuxes?

**Comment by sunnya97** [comment]
Oh right.

Ok, so main assetlist should use no prefix/suffix

Frontier should use USDC.axl and USDC.grv
